"""empty message

Revision ID: 0c31fd9441b4
Revises: 6058c2f97c91
Create Date: 2023-12-08 11:51:52.301607

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c31fd9441b4"
down_revision: Union[str, None] = "6058c2f97c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "subjects",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "students",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("f_name", sa.String(length=250), nullable=False),
        sa.Column("l_name", sa.String(length=250), nullable=False),
        sa.Column("stud_group", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stud_group"],
            ["groups.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "teachers",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("f_name", sa.String(length=250), nullable=False),
        sa.Column("l_name", sa.String(length=250), nullable=False),
        sa.Column("subject", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject"],
            ["subjects.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "grades",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("student_pk", sa.SmallInteger(), nullable=True),
        sa.Column("subject_pk", sa.SmallInteger(), nullable=True),
        sa.Column("teacher_pk", sa.SmallInteger(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_pk"],
            ["students.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_pk"],
            ["subjects.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_pk"],
            ["teachers.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grades")
    op.drop_table("teachers")
    op.drop_table("students")
    op.drop_table("subjects")
    op.drop_table("groups")
    # ### end Alembic commands ###
