"""subject remove teachers

Revision ID: 48a138880204
Revises: 582e4323587d
Create Date: 2023-12-08 11:28:24.120971

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48a138880204"
down_revision: Union[str, None] = "582e4323587d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subjects_teachers_fkey", "subjects", type_="foreignkey")
    op.drop_column("subjects", "teachers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column("teachers", sa.SMALLINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "subjects_teachers_fkey", "subjects", "teachers", ["teachers"], ["pk"]
    )
    # ### end Alembic commands ###
