"""Grade dbg

Revision ID: 6058c2f97c91
Revises: ee5e0a1a5bea
Create Date: 2023-12-08 11:40:40.139613

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6058c2f97c91"
down_revision: Union[str, None] = "ee5e0a1a5bea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grades", sa.Column("subject_pk", sa.SmallInteger(), nullable=True))
    op.drop_constraint("grades_class_pk_fkey", "grades", type_="foreignkey")
    op.create_foreign_key(None, "grades", "subjects", ["subject_pk"], ["pk"])
    op.drop_column("grades", "class_pk")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grades",
        sa.Column("class_pk", sa.SMALLINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "grades", type_="foreignkey")
    op.create_foreign_key(
        "grades_class_pk_fkey", "grades", "subjects", ["class_pk"], ["pk"]
    )
    op.drop_column("grades", "subject_pk")
    # ### end Alembic commands ###
