"""init

Revision ID: 670e5e3070df
Revises: a92bc9b30ffd
Create Date: 2023-12-08 11:07:05.366481

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "670e5e3070df"
down_revision: Union[str, None] = "a92bc9b30ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("f_name", sa.String(length=250), nullable=False),
        sa.Column("l_name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("teachers", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teachers"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("f_name", sa.String(length=250), nullable=False),
        sa.Column("l_name", sa.String(length=250), nullable=False),
        sa.Column("stud_group", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stud_group"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("class_id", sa.SmallInteger(), nullable=True),
        sa.Column("teacher_id", sa.SmallInteger(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grades")
    op.drop_table("students")
    op.drop_table("classes")
    op.drop_table("teachers")
    op.drop_table("groups")
    # ### end Alembic commands ###
