"""teachers foreign key

Revision ID: 85c8d880202a
Revises: d233065df5e2
Create Date: 2023-12-08 11:25:10.919661

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85c8d880202a"
down_revision: Union[str, None] = "d233065df5e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teachers", sa.Column("subjects", sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, "teachers", "subjects", ["subjects"], ["pk"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.drop_column("teachers", "subjects")
    # ### end Alembic commands ###
