# Generated by Django 5.0 on 2023-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
