# Generated by Django 5.0 on 2023-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_by",
            field=models.IntegerField(default=2, verbose_name="created by user id"),
        ),
        migrations.AddField(
            model_name="quote",
            name="created_by",
            field=models.IntegerField(default=2, verbose_name="created by user id"),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.IntegerField(default=2, verbose_name="created by user id"),
        ),
    ]
